#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="test")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVacaion(Vacaion instance);
    partial void UpdateVacaion(Vacaion instance);
    partial void DeleteVacaion(Vacaion instance);
    #endregion
		
		public dbDataContext() : 
				base(global::DAL.Properties.Settings.Default.testConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Department> Departments
		{
			get
			{
				return this.GetTable<Department>();
			}
		}
		
		public System.Data.Linq.Table<Vacaion> Vacaions
		{
			get
			{
				return this.GetTable<Vacaion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetVacancies")]
		public ISingleResult<GetVacanciesResult> GetVacancies()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetVacanciesResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Department")]
	public partial class Department
	{
		
		private System.Nullable<int> _id;
		
		private string _name;
		
		public Department()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vacaion")]
	public partial class Vacaion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _VacancyId;
		
		private System.Nullable<System.DateTime> _SubmissionDate;
		
		private string _EmployeeName;
		
		private string _Title;
		
		private System.Nullable<int> _Department;
		
		private System.Nullable<System.DateTime> _VacationDateFrom;
		
		private System.Nullable<System.DateTime> _VacationDateTo;
		
		private System.Nullable<System.DateTime> _Returning;
		
		private string _Notes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVacancyIdChanging(System.Guid value);
    partial void OnVacancyIdChanged();
    partial void OnSubmissionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSubmissionDateChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDepartmentChanging(System.Nullable<int> value);
    partial void OnDepartmentChanged();
    partial void OnVacationDateFromChanging(System.Nullable<System.DateTime> value);
    partial void OnVacationDateFromChanged();
    partial void OnVacationDateToChanging(System.Nullable<System.DateTime> value);
    partial void OnVacationDateToChanged();
    partial void OnReturningChanging(System.Nullable<System.DateTime> value);
    partial void OnReturningChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public Vacaion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacancyId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid VacancyId
		{
			get
			{
				return this._VacancyId;
			}
			set
			{
				if ((this._VacancyId != value))
				{
					this.OnVacancyIdChanging(value);
					this.SendPropertyChanging();
					this._VacancyId = value;
					this.SendPropertyChanged("VacancyId");
					this.OnVacancyIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmissionDate
		{
			get
			{
				return this._SubmissionDate;
			}
			set
			{
				if ((this._SubmissionDate != value))
				{
					this.OnSubmissionDateChanging(value);
					this.SendPropertyChanging();
					this._SubmissionDate = value;
					this.SendPropertyChanged("SubmissionDate");
					this.OnSubmissionDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(50)")]
		public string EmployeeName
		{
			get
			{
				return this._EmployeeName;
			}
			set
			{
				if ((this._EmployeeName != value))
				{
					this.OnEmployeeNameChanging(value);
					this.SendPropertyChanging();
					this._EmployeeName = value;
					this.SendPropertyChanged("EmployeeName");
					this.OnEmployeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Int")]
		public System.Nullable<int> Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacationDateFrom", DbType="DateTime")]
		public System.Nullable<System.DateTime> VacationDateFrom
		{
			get
			{
				return this._VacationDateFrom;
			}
			set
			{
				if ((this._VacationDateFrom != value))
				{
					this.OnVacationDateFromChanging(value);
					this.SendPropertyChanging();
					this._VacationDateFrom = value;
					this.SendPropertyChanged("VacationDateFrom");
					this.OnVacationDateFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacationDateTo", DbType="DateTime")]
		public System.Nullable<System.DateTime> VacationDateTo
		{
			get
			{
				return this._VacationDateTo;
			}
			set
			{
				if ((this._VacationDateTo != value))
				{
					this.OnVacationDateToChanging(value);
					this.SendPropertyChanging();
					this._VacationDateTo = value;
					this.SendPropertyChanged("VacationDateTo");
					this.OnVacationDateToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Returning", DbType="DateTime")]
		public System.Nullable<System.DateTime> Returning
		{
			get
			{
				return this._Returning;
			}
			set
			{
				if ((this._Returning != value))
				{
					this.OnReturningChanging(value);
					this.SendPropertyChanging();
					this._Returning = value;
					this.SendPropertyChanged("Returning");
					this.OnReturningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(50)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetVacanciesResult
	{
		
		private System.Guid _VacancyId;
		
		private System.Nullable<System.DateTime> _SubmissionDate;
		
		private string _EmployeeName;
		
		private string _Title;
		
		private System.Nullable<int> _Department;
		
		private System.Nullable<System.DateTime> _VacationDateFrom;
		
		private System.Nullable<System.DateTime> _VacationDateTo;
		
		private System.Nullable<System.DateTime> _Returning;
		
		private string _Notes;
		
		private System.Nullable<int> _id;
		
		private string _name;
		
		public GetVacanciesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacancyId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid VacancyId
		{
			get
			{
				return this._VacancyId;
			}
			set
			{
				if ((this._VacancyId != value))
				{
					this._VacancyId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubmissionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SubmissionDate
		{
			get
			{
				return this._SubmissionDate;
			}
			set
			{
				if ((this._SubmissionDate != value))
				{
					this._SubmissionDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(50)")]
		public string EmployeeName
		{
			get
			{
				return this._EmployeeName;
			}
			set
			{
				if ((this._EmployeeName != value))
				{
					this._EmployeeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(50)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="Int")]
		public System.Nullable<int> Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this._Department = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacationDateFrom", DbType="DateTime")]
		public System.Nullable<System.DateTime> VacationDateFrom
		{
			get
			{
				return this._VacationDateFrom;
			}
			set
			{
				if ((this._VacationDateFrom != value))
				{
					this._VacationDateFrom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VacationDateTo", DbType="DateTime")]
		public System.Nullable<System.DateTime> VacationDateTo
		{
			get
			{
				return this._VacationDateTo;
			}
			set
			{
				if ((this._VacationDateTo != value))
				{
					this._VacationDateTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Returning", DbType="DateTime")]
		public System.Nullable<System.DateTime> Returning
		{
			get
			{
				return this._Returning;
			}
			set
			{
				if ((this._Returning != value))
				{
					this._Returning = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(50)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this._Notes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
